#!/usr/bin/env python3
"""Generate a dependency-free, compiled fallback; --check is used by CI."""
import argparse
from pathlib import Path
root = Path(__file__).resolve().parents[1]
source = (root / "Sources/TkTracker/Resources/pricing.json").read_text().strip()
output = '// Generated by Scripts/generate_pricing.py. Do not edit.\n' + 'enum BundledPricing {\n    static let json = #"""\n' + source + '\n"""#\n}\n'
target = root / "Sources/TkTracker/Core/BundledPricing.swift"
parser = argparse.ArgumentParser()
parser.add_argument("--check", action="store_true")
args = parser.parse_args()
if args.check:
    if not target.exists() or target.read_text() != output:
        raise SystemExit("Bundled pricing is stale: run python3 Scripts/generate_pricing.py")
else:
    target.write_text(output)
