// Generated by Scripts/generate_pricing.py. Do not edit.
enum BundledPricing {
    static let json = #"""
{
  "schema": 2,
  "updated": "2026-09-07",
  "note": "USD per million tokens. Exact canonical IDs and explicit cache rates. Unknown service tiers use standard estimates; unsupported observed fast modes remain unpriced.",
  "webSearchPer1000": 10,
  "contextWindows": [],
  "defaultContextWindow": 200000,
  "rules": [
    {
      "match": [],
      "ids": [
        "gpt-6-astra"
      ],
      "vendor": "openai",
      "input": 10,
      "output": 50,
      "cacheRead": 1.0,
      "cacheWrite5m": 12.5,
      "cacheWrite1h": 12.5,
      "contextWindow": 1050000,
      "sourceURL": "https://developers.openai.com/api/docs/pricing",
      "longContextThreshold": 272000,
      "fastMultiplier": 2
    },
    {
      "match": [],
      "ids": [
        "gpt-5.6-sol"
      ],
      "vendor": "openai",
      "input": 4,
      "output": 20,
      "cacheRead": 0.4,
      "cacheWrite5m": 5.0,
      "cacheWrite1h": 5.0,
      "contextWindow": 1050000,
      "sourceURL": "https://developers.openai.com/api/docs/pricing",
      "longContextThreshold": 272000,
      "fastMultiplier": 2,
      "reviewAfter": "2026-11-21"
    },
    {
      "match": [],
      "ids": [
        "gpt-5.6-terra"
      ],
      "vendor": "openai",
      "input": 2,
      "output": 12,
      "cacheRead": 0.2,
      "cacheWrite5m": 2.5,
      "cacheWrite1h": 2.5,
      "contextWindow": 1050000,
      "sourceURL": "https://developers.openai.com/api/docs/pricing",
      "longContextThreshold": 272000,
      "fastMultiplier": 2
    },
    {
      "match": [],
      "ids": [
        "gpt-5.6-luna"
      ],
      "vendor": "openai",
      "input": 0.2,
      "output": 1.2,
      "cacheRead": 0.02,
      "cacheWrite5m": 0.25,
      "cacheWrite1h": 0.25,
      "contextWindow": 1050000,
      "sourceURL": "https://developers.openai.com/api/docs/pricing",
      "longContextThreshold": 272000,
      "fastMultiplier": 2
    },
    {
      "match": [],
      "ids": [
        "gpt-5.6-cyber"
      ],
      "vendor": "openai",
      "input": 12.5,
      "output": 75,
      "cacheRead": 1.25,
      "cacheWrite5m": 15.625,
      "cacheWrite1h": 15.625,
      "contextWindow": 272000,
      "sourceURL": "https://developers.openai.com/api/docs/pricing"
    },
    {
      "match": [],
      "ids": [
        "gpt-5.5"
      ],
      "vendor": "openai",
      "input": 5,
      "output": 30,
      "cacheRead": 0.5,
      "cacheWrite5m": 0,
      "cacheWrite1h": 0,
      "contextWindow": 1050000,
      "sourceURL": "https://developers.openai.com/api/docs/pricing",
      "longContextThreshold": 272000,
      "fastMultiplier": 2
    },
    {
      "match": [],
      "ids": [
        "gpt-5.4"
      ],
      "vendor": "openai",
      "input": 2.5,
      "output": 15,
      "cacheRead": 0.25,
      "cacheWrite5m": 0,
      "cacheWrite1h": 0,
      "contextWindow": 1050000,
      "sourceURL": "https://developers.openai.com/api/docs/pricing",
      "longContextThreshold": 272000,
      "fastMultiplier": 2
    },
    {
      "match": [],
      "ids": [
        "gpt-5.4-mini"
      ],
      "vendor": "openai",
      "input": 0.75,
      "output": 4.5,
      "cacheRead": 0.075,
      "cacheWrite5m": 0,
      "cacheWrite1h": 0,
      "contextWindow": 272000,
      "sourceURL": "https://developers.openai.com/api/docs/pricing"
    },
    {
      "match": [],
      "ids": [
        "gpt-5.4-nano"
      ],
      "vendor": "openai",
      "input": 0.2,
      "output": 1.25,
      "cacheRead": 0.02,
      "cacheWrite5m": 0,
      "cacheWrite1h": 0,
      "contextWindow": 272000,
      "sourceURL": "https://developers.openai.com/api/docs/pricing"
    },
    {
      "match": [],
      "ids": [
        "gpt-5.3",
        "gpt-5.3-codex"
      ],
      "vendor": "openai",
      "input": 1.75,
      "output": 14,
      "cacheRead": 0.175,
      "cacheWrite5m": 0,
      "cacheWrite1h": 0,
      "contextWindow": 272000,
      "sourceURL": "https://developers.openai.com/api/docs/pricing"
    },
    {
      "match": [],
      "ids": [
        "gpt-5.2",
        "gpt-5.2-codex"
      ],
      "vendor": "openai",
      "input": 1.75,
      "output": 14,
      "cacheRead": 0.175,
      "cacheWrite5m": 0,
      "cacheWrite1h": 0,
      "contextWindow": 272000,
      "sourceURL": "https://developers.openai.com/api/docs/pricing"
    },
    {
      "match": [],
      "ids": [
        "gpt-5",
        "gpt-5-codex",
        "gpt-5.1",
        "gpt-5.1-codex",
        "gpt-5.1-codex-max"
      ],
      "vendor": "openai",
      "input": 1.25,
      "output": 10,
      "cacheRead": 0.125,
      "cacheWrite5m": 0,
      "cacheWrite1h": 0,
      "contextWindow": 272000,
      "sourceURL": "https://developers.openai.com/api/docs/pricing"
    },
    {
      "match": [],
      "ids": [
        "gpt-5-mini",
        "gpt-5.1-codex-mini"
      ],
      "vendor": "openai",
      "input": 0.25,
      "output": 2,
      "cacheRead": 0.025,
      "cacheWrite5m": 0,
      "cacheWrite1h": 0,
      "contextWindow": 272000,
      "sourceURL": "https://developers.openai.com/api/docs/pricing"
    },
    {
      "match": [],
      "ids": [
        "gpt-5-nano"
      ],
      "vendor": "openai",
      "input": 0.05,
      "output": 0.4,
      "cacheRead": 0.005,
      "cacheWrite5m": 0,
      "cacheWrite1h": 0,
      "contextWindow": 272000,
      "sourceURL": "https://developers.openai.com/api/docs/pricing"
    },
    {
      "match": [],
      "ids": [
        "codex-mini-latest"
      ],
      "vendor": "openai",
      "input": 1.5,
      "output": 6,
      "cacheRead": 0.375,
      "cacheWrite5m": 0,
      "cacheWrite1h": 0,
      "contextWindow": 272000,
      "sourceURL": "https://developers.openai.com/api/docs/pricing"
    },
    {
      "match": [],
      "ids": [
        "claude-fable-5-1",
        "claude-mythos-5-1"
      ],
      "vendor": "anthropic",
      "input": 10,
      "output": 50,
      "cacheRead": 0.25,
      "cacheWrite5m": 12.5,
      "cacheWrite1h": 20,
      "contextWindow": 1000000,
      "sourceURL": "https://platform.claude.com/docs/en/about-claude/pricing"
    },
    {
      "match": [],
      "ids": [
        "claude-fable-5",
        "claude-mythos-5"
      ],
      "vendor": "anthropic",
      "input": 10,
      "output": 50,
      "cacheRead": 1.0,
      "cacheWrite5m": 12.5,
      "cacheWrite1h": 20,
      "contextWindow": 1000000,
      "sourceURL": "https://platform.claude.com/docs/en/about-claude/pricing"
    },
    {
      "match": [],
      "ids": [
        "claude-opus-5",
        "claude-opus-4-8"
      ],
      "vendor": "anthropic",
      "input": 5,
      "output": 25,
      "cacheRead": 0.5,
      "cacheWrite5m": 6.25,
      "cacheWrite1h": 10,
      "contextWindow": 1000000,
      "sourceURL": "https://platform.claude.com/docs/en/about-claude/pricing",
      "fastMultiplier": 2
    },
    {
      "match": [],
      "ids": [
        "claude-opus-4-6"
      ],
      "vendor": "anthropic",
      "input": 5,
      "output": 25,
      "cacheRead": 0.5,
      "cacheWrite5m": 6.25,
      "cacheWrite1h": 10,
      "contextWindow": 1000000,
      "sourceURL": "https://platform.claude.com/docs/en/about-claude/pricing",
      "fastMultiplier": 1
    },
    {
      "match": [],
      "ids": [
        "claude-opus-4-7"
      ],
      "vendor": "anthropic",
      "input": 5,
      "output": 25,
      "cacheRead": 0.5,
      "cacheWrite5m": 6.25,
      "cacheWrite1h": 10,
      "contextWindow": 1000000,
      "sourceURL": "https://platform.claude.com/docs/en/about-claude/pricing"
    },
    {
      "match": [],
      "ids": [
        "claude-opus-4-5"
      ],
      "vendor": "anthropic",
      "input": 5,
      "output": 25,
      "cacheRead": 0.5,
      "cacheWrite5m": 6.25,
      "cacheWrite1h": 10,
      "contextWindow": 200000,
      "sourceURL": "https://platform.claude.com/docs/en/about-claude/pricing"
    },
    {
      "match": [],
      "ids": [
        "claude-opus-4-1",
        "claude-opus-4",
        "claude-3-opus"
      ],
      "vendor": "anthropic",
      "input": 15,
      "output": 75,
      "cacheRead": 1.5,
      "cacheWrite5m": 18.75,
      "cacheWrite1h": 30,
      "contextWindow": 200000,
      "sourceURL": "https://platform.claude.com/docs/en/about-claude/pricing"
    },
    {
      "match": [],
      "ids": [
        "claude-sonnet-5"
      ],
      "vendor": "anthropic",
      "input": 2,
      "output": 10,
      "cacheRead": 0.2,
      "cacheWrite5m": 2.5,
      "cacheWrite1h": 4,
      "contextWindow": 1000000,
      "sourceURL": "https://platform.claude.com/docs/en/about-claude/pricing"
    },
    {
      "match": [],
      "ids": [
        "claude-sonnet-4-6"
      ],
      "vendor": "anthropic",
      "input": 3,
      "output": 15,
      "cacheRead": 0.3,
      "cacheWrite5m": 3.75,
      "cacheWrite1h": 6,
      "contextWindow": 1000000,
      "sourceURL": "https://platform.claude.com/docs/en/about-claude/pricing"
    },
    {
      "match": [],
      "ids": [
        "claude-sonnet-4-5",
        "claude-sonnet-4",
        "claude-3-7-sonnet",
        "claude-3-5-sonnet",
        "claude-3-sonnet"
      ],
      "vendor": "anthropic",
      "input": 3,
      "output": 15,
      "cacheRead": 0.3,
      "cacheWrite5m": 3.75,
      "cacheWrite1h": 6,
      "contextWindow": 200000,
      "sourceURL": "https://platform.claude.com/docs/en/about-claude/pricing"
    },
    {
      "match": [],
      "ids": [
        "claude-haiku-4-5"
      ],
      "vendor": "anthropic",
      "input": 1,
      "output": 5,
      "cacheRead": 0.1,
      "cacheWrite5m": 1.25,
      "cacheWrite1h": 2,
      "contextWindow": 200000,
      "sourceURL": "https://platform.claude.com/docs/en/about-claude/pricing"
    },
    {
      "match": [],
      "ids": [
        "claude-3-5-haiku",
        "claude-haiku-3-5"
      ],
      "vendor": "anthropic",
      "input": 0.8,
      "output": 4,
      "cacheRead": 0.08,
      "cacheWrite5m": 1.0,
      "cacheWrite1h": 1.6,
      "contextWindow": 200000,
      "sourceURL": "https://platform.claude.com/docs/en/about-claude/pricing"
    },
    {
      "match": [],
      "ids": [
        "claude-3-haiku"
      ],
      "vendor": "anthropic",
      "input": 0.25,
      "output": 1.25,
      "cacheRead": 0.025,
      "cacheWrite5m": 0.3125,
      "cacheWrite1h": 0.5,
      "contextWindow": 200000,
      "sourceURL": "https://platform.claude.com/docs/en/about-claude/pricing"
    },
    {
      "match": [],
      "ids": [
        "claude-2",
        "claude-2.0",
        "claude-2.1"
      ],
      "vendor": "anthropic",
      "input": 8,
      "output": 24,
      "cacheRead": 0.8,
      "cacheWrite5m": 10.0,
      "cacheWrite1h": 16,
      "contextWindow": 200000,
      "sourceURL": "https://platform.claude.com/docs/en/about-claude/pricing"
    },
    {
      "match": [],
      "ids": [
        "claude-instant-1",
        "claude-instant-1.2"
      ],
      "vendor": "anthropic",
      "input": 0.8,
      "output": 2.4,
      "cacheRead": 0.08,
      "cacheWrite5m": 1.0,
      "cacheWrite1h": 1.6,
      "contextWindow": 200000,
      "sourceURL": "https://platform.claude.com/docs/en/about-claude/pricing"
    }
  ]
}
"""#
}
